"""Add agent command queue

Revision ID: 24a7fc608b1d
Revises: a2b137009bdb
Create Date: 2026-08-21 09:11:59.342308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a7fc608b1d'
down_revision: Union[str, None] = 'a2b137009bdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('command_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_commands_id'), 'agent_commands', ['id'], unique=False)
    op.create_index(op.f('ix_agent_commands_machine_id'), 'agent_commands', ['machine_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_commands_machine_id'), table_name='agent_commands')
    op.drop_index(op.f('ix_agent_commands_id'), table_name='agent_commands')
    op.drop_table('agent_commands')
    # ### end Alembic commands ###
