"""Add safe schema updates

Revision ID: 2ef2a49e2b84
Revises: b7ff51fc8836
Create Date: 2026-08-24 11:00:15.722226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef2a49e2b84'
down_revision: Union[str, None] = 'b7ff51fc8836'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
