"""Add safe updated_at and command output

Revision ID: b7ff51fc8836
Revises: 24a7fc608b1d
Create Date: 2026-08-24 10:58:24.453490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7ff51fc8836'
down_revision: Union[str, None] = '24a7fc608b1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('log_level', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_entries_id'), 'log_entries', ['id'], unique=False)
    op.create_index(op.f('ix_log_entries_machine_id'), 'log_entries', ['machine_id'], unique=False)
    op.create_index(op.f('ix_log_entries_timestamp'), 'log_entries', ['timestamp'], unique=False)
    op.drop_index('ix_logs_id', table_name='logs')
    op.drop_index('ix_logs_level', table_name='logs')
    op.drop_index('ix_logs_machine_id', table_name='logs')
    op.drop_index('ix_logs_timestamp', table_name='logs')
    op.drop_table('logs')
    op.add_column('agent_commands', sa.Column('result_output', sa.Text(), nullable=True))
    op.alter_column('ai_analyses', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('ai_analyses', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('ai_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('incidents', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('incidents', 'category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_incidents_created_at'), 'incidents', ['created_at'], unique=False)
    op.drop_constraint('incidents_assigned_user_id_fkey', 'incidents', type_='foreignkey')
    op.drop_column('incidents', 'assigned_user_id')
    op.alter_column('machine_metrics', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.add_column('machines', sa.Column('logged_in_user', sa.String(length=100), nullable=True))
    op.add_column('machines', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('machines', 'os_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('machines', 'agent_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('machines', 'last_heartbeat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('machines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_machines_hostname'), 'machines', ['hostname'], unique=False)
    op.alter_column('network_metrics', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('process_snapshots', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_process_snapshots_timestamp'), 'process_snapshots', ['timestamp'], unique=False)
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_index(op.f('ix_process_snapshots_timestamp'), table_name='process_snapshots')
    op.alter_column('process_snapshots', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('network_metrics', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.drop_index(op.f('ix_machines_hostname'), table_name='machines')
    op.alter_column('machines', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('machines', 'last_heartbeat',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('machines', 'agent_version',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('machines', 'os_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('machines', 'updated_at')
    op.drop_column('machines', 'logged_in_user')
    op.alter_column('machine_metrics', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.add_column('incidents', sa.Column('assigned_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('incidents_assigned_user_id_fkey', 'incidents', 'users', ['assigned_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_incidents_created_at'), table_name='incidents')
    op.alter_column('incidents', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('incidents', 'category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('incidents', 'updated_at')
    op.alter_column('ai_analyses', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('ai_analyses', 'model_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('ai_analyses', 'confidence_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('agent_commands', 'result_output')
    op.create_table('logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('machine_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('level', postgresql.ENUM('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel'), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata_json', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name='logs_machine_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='logs_pkey')
    )
    op.create_index('ix_logs_timestamp', 'logs', ['timestamp'], unique=False)
    op.create_index('ix_logs_machine_id', 'logs', ['machine_id'], unique=False)
    op.create_index('ix_logs_level', 'logs', ['level'], unique=False)
    op.create_index('ix_logs_id', 'logs', ['id'], unique=False)
    op.drop_index(op.f('ix_log_entries_timestamp'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_machine_id'), table_name='log_entries')
    op.drop_index(op.f('ix_log_entries_id'), table_name='log_entries')
    op.drop_table('log_entries')
    # ### end Alembic commands ###
